### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by eerwitt** [inikulin/esotope#2]
I am impressed by this library.

I use escodegen for projects in the browser and I am wondering if you have considered adding a build step for browser support?

Thank you

**Comment by inikulin** [comment]
Hi @eerwitt.
Thank you for the kind words. I've just landed browser support. Please, see updated [Install section](https://github.com/inikulin/esotope#install) for the detalis.

**Comment by eerwitt** [comment]
Awesome! Thank you.

**Comment by inikulin** [comment]
@eerwitt You are welcome!

**Comment by inikulin** [comment]
@eerwitt Sorry, I mean [Install section](https://github.com/inikulin/esotope#install)
