### ISSUE TITLE
new release with browser support?

### ISSUE THREAD

**Issue by msridhar** [inikulin/esotope#4]
I see that support for running esotope in the browser has been added in GitHub.  Would it be possible to `npm publish` a new release with this functionality?  We are working on a project that requires using the code generator both on node and in the browser, so this would be very helpful to us.  Thanks!

**Comment by inikulin** [comment]
Hi,

I've published new version 1.4.4 to npm.

**Comment by msridhar** [comment]
Great, thanks!
